name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: timescale/timescaledb:latest-pg14
        ports: [5432:5432]
        env:
          POSTGRES_USER: khalil
          POSTGRES_PASSWORD: MyStrongPass123
          POSTGRES_DB: volatility_db
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r predictor/requirements.txt

    - name: Run Unit Tests (if any)
      run: |
        echo "🧪 Add pytest or other test scripts here"

    - name: Build Docker Images
      run: docker-compose build

    - name: Run Lint Checks
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Streamlit or Service (Optional Smoke Test)
      run: |
        docker-compose up -d
        sleep 10
        docker ps